In [3]:
import pandas as pd

In [5]:
nba_df = pd.read_csv('NBA_AMLAA_Assignment1/data/raw/train.csv', low_memory=False)

In [6]:
nba_df.head()

,team,conf,GP,Min_per,Ortg,usg,eFG,TS_per,ORB_per,DRB_per,...,dgbpm,oreb,dreb,treb,ast,stl,blk,pts,player_id,drafted
0,South Alabama,SB,26,29.5,97.3,16.6,42.5,44.43,1.6,4.6,...,-1.941150,0.1923,0.6154,0.8077,1.1923,0.3462,0.0385,3.8846,b2716b2d-3422-4959-9fe7-fe496414a4e8,0.0
1,Utah St.,WAC,34,60.9,108.3,14.9,52.4,54.48,3.8,6.3,...,-0.247934,0.6765,1.2647,1.9412,1.8235,0.4118,0.2353,5.9412,bb387960-e3a0-4ffd-96ae-184bad07cb8a,0.0
2,South Florida,BE,27,72.0,96.2,21.8,45.7,47.98,2.1,8.0,...,-0.883163,0.6296,2.3333,2.9630,1.9630,0.4815,0.0000,12.1852,89bbdf11-eadd-4de4-95e5-03f7e2874aa1,0.0
3,Pepperdine,WCC,30,44.5,97.7,16.0,53.6,53.69,4.1,9.4,...,-0.393459,0.7000,1.4333,2.1333,1.1000,0.5667,0.1333,4.9333,0c87ada8-8446-4ea2-a05b-bd07aed5f37a,0.0
4,Pacific,BW,33,56.2,96.5,22.0,52.8,54.31,8.3,18.6,...,-0.668318,1.4242,3.3030,4.7273,0.8485,0.4545,0.3333,7.5758,84661e00-ad20-4308-817e-efa8da52a86c,0.0

# Data Cleaning

In [12]:
missing_nbda_df_values = nba_df.isnull().sum()
percentage_missing = (nba_df.isnull().sum() / len(nba_df)) * 100

missing_values_df = pd.DataFrame({'missing_values': missing_nbda_df_values, 'percentage_of_missing_values': percentage_missing})

missing_values_df

           missing_values  percentage_of_missing_values
team                    0                      0.000000
conf                    0                      0.000000
GP                      0                      0.000000
Min_per                 0                      0.000000
Ortg                    0                      0.000000
...                   ...                           ...
stl                    36                      0.077223
blk                    36                      0.077223
pts                    36                      0.077223
player_id               0                      0.000000
drafted                 0                      0.000000

[64 rows x 2 columns]